language: scala

dist: xenial

scala:
   - 2.12.8

services:
  - postgresql

jobs:
  include:
      before_script:
        - psql -c 'create database api_test;' -U postgres
        - sbt stage

      script:
        - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
        - ./build.sh

      after_success:
        - bash <(curl -s https://codecov.io/bash)
